// @ts-check

/**
 * Curated sidebar for the OpenLM Platform (cloud) docs.
 *
 * The daily-use band mirrors the in-app "All Applications" launcher: each
 * top-level section uses the launcher's own category name, and every launcher
 * app is listed under the category the app itself puts it in. The onboarding
 * journey (Get started → Deployment → Connect data sources) stays on top, and
 * docs-only areas (For end users, MCP Connector, Reference, Changelog) sit
 * below the mirrored core.
 *
 *   Get started → Deployment & operations → Connect data sources →
 *   Licenses and Features → Users → Agents → Platform Administration →
 *   Software Asset Management → Integrations → BI Reports →
 *   For end users → OpenLM MCP Connector → Reference → Changelog
 *
 * Files stay where they are on disk — this sidebar only controls grouping and
 * order, so existing page URLs and their redirects are preserved. Only the
 * generated-index category URLs (/cloud/category/<slug>) change with the
 * labels; those are redirected in docusaurus.config.js.
 *
 * Because several sections pull docs out of their on-disk folder (e.g. License
 * Access Control lives in automations/ but belongs to Licenses and Features),
 * those sections are hand-listed by doc ID rather than autogenerated. A new
 * page dropped into one of those folders must also be added here by hand.
 *
 * Not listed: automations/anonymization.md (draft: true — excluded from the
 * production build) and the understanding-openlm/ drafts.
 */

/**
 * Wrap an autogenerated folder in an explicit category so the category index
 * page is always generated at /cloud/category/<slug of label>.
 */
const section = (label, dirName, description) => ({
  type: 'category',
  label,
  link: {
    type: 'generated-index',
    ...(description ? { description } : {}),
  },
  items: [{ type: 'autogenerated', dirName }],
});

/**
 * A hand-listed category: explicit items (doc IDs and/or nested categories),
 * with a generated-index landing page at /cloud/category/<slug of label>.
 */
const group = (label, items, description) => ({
  type: 'category',
  label,
  link: {
    type: 'generated-index',
    ...(description ? { description } : {}),
  },
  items,
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    section('Get started', 'getting-started'),

    // Deployment & operations keeps its whole subtree; the Database
    // Configuration Tool (an installer-side utility, not a launcher app) is
    // parked here rather than in Platform Administration.
    group('Deployment and operations', [
      { type: 'autogenerated', dirName: 'deployment-operations' },
      'openlm-administration/database-configuration-tool',
    ]),

    // Journey label; the launcher's own words ("Brokers") surface inside.
    group('Connect data sources', [
      group('Brokers', [
        'data-collection/broker-hub',
        'data-collection/openlm-broker',
        'data-collection/cloud-broker',
      ]),
      group('Connect license managers', [
        { type: 'autogenerated', dirName: 'data-collection/connect-license-managers' },
      ]),
    ]),

    // Launcher category "Licenses and Features" (10 apps, launcher order);
    // Subscription Optimizer (no dedicated UI, configured through LAC) rides
    // along at the end.
    group('Licenses and Features', [
      'slm/licenses',
      'automations/license-access-control',
      'slm/license-servers',
      'slm/license-allocations',
      'reporting/ui-reports/usage',
      'compliance',
      'reporting/ui-reports/denials',
      'lfm',
      'vlm',
      'license-parser',
      'automations/subscription-optimizer',
    ]),

    // Launcher category "Users"; Personal Dashboard (admin setup, delivered by
    // Workstation Agent — not a launcher tile) is appended.
    group('Users', [
      'users/users-and-groups',
      'users/projects',
      'users/directory-sync',
      'users/ldap-connector',
      'automations/identity-alignment',
      'users/personal-dashboard',
    ]),

    // Launcher category "Agents" — reunites the six apps that were previously
    // scattered across Data collection, License tools, Automations, Reporting.
    group('Agents', [
      'data-collection/workstation-agent',
      'data-collection/agents_hub',
      'data-collection/agent_activity_manager',
      'dongle-monitoring',
      'reporting/ui-reports/process-sessions',
      'automations/process-manager',
      'reporting/ui-reports/touch-point-events',
    ]),

    // Launcher category "Platform Administration" (7 apps, launcher order).
    group('Platform Administration', [
      'automations/alerts',
      'openlm-administration/audit',
      'openlm-administration/identity',
      'openlm-administration/license-manager',
      'automations/notifications',
      'openlm-administration/products',
      'openlm-administration/ui-configuration',
    ]),

    // Launcher category "Software Asset Management". SAM Catalog is a launcher
    // app with no page yet — add its doc ID here once written.
    group('Software Asset Management', ['sam', 'sam-catalog']),

    section('Integrations', 'integrations'),

    // Mirrors the launcher's "BI Reports" header shortcut. The threshold-alerts
    // how-to is a BI-surface guide, so it lives here rather than loose at the
    // Reporting root. The docs-invented "UI reports" grouping is dissolved —
    // its four pages moved to Licenses and Features and Agents above.
    group('BI Reports', [
      { type: 'autogenerated', dirName: 'reporting/bi-reports' },
      'reporting/configuring-threshold-alerts-in-amazon-quick-suite',
    ]),

    section(
      'For end users',
      'for-end-users',
      'Guides for day-to-day use of OpenLM — checking license availability, understanding your dashboard, and what to do when you get a denial.'
    ),

    section('OpenLM MCP Connector', 'mcp-reporting-server'),

    group(
      'Reference',
      [
        group('API reference', [{ type: 'autogenerated', dirName: 'api' }]),
        'glossary',
        'service-index',
      ],
      'API, glossary, and service index for the OpenLM Platform.'
    ),

    section('Changelog', 'changelog'),
  ],
};

module.exports = sidebars;
