// @ts-check

/**
 * Curated sidebar for the OpenLM Platform (cloud) docs.
 *
 * Top-level order follows the user journey:
 *   Get Started → Deployment & Operations → Data Collection →
 *   Administration → User Management → License tools → Reporting →
 *   Automations → Integrations → For End Users → Reference → Changelog
 *
 * Understanding OpenLM is omitted because its folder only contains
 * underscore-prefixed drafts; re-add a section() entry once content exists.
 *
 * Files stay where they are on disk — this sidebar only controls grouping
 * and order, so existing URLs and redirects are preserved. Each top-level
 * section is wrapped in an explicit category so its `generated-index`
 * landing page (/cloud/category/<slug>) keeps working. Nested ordering
 * inside each category still honors `_category_.json` and `sidebar_position`.
 */

/**
 * Wrap an autogenerated folder in an explicit category so the category
 * index page is always generated at /cloud/category/<slug of label>.
 */
const section = (label, dirName, description) => ({
  type: 'category',
  label,
  link: {
    type: 'generated-index',
    ...(description ? { description } : {}),
  },
  items: [{ type: 'autogenerated', dirName }],
});

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    section('Get started', 'getting-started'),
    section('Deployment and operations', 'deployment-operations'),
    section('Data collection', 'data-collection'),
    section('OpenLM administration', 'openlm-administration'),
    section('User management', 'users'),
    {
      type: 'category',
      label: 'License tools',
      link: {
        type: 'generated-index',
        description:
          'OpenLM modules for tracking and managing specific license types, dongles, and compliance scenarios.',
      },
      items: [
        {
          type: 'category',
          label: 'Software License Manager (SLM)',
          link: { type: 'generated-index' },
          items: [{ type: 'autogenerated', dirName: 'slm' }],
        },
        'lfm',
        'vlm',
        'sam',
        'compliance',
        'dongle-monitoring',
      ],
    },
    section('Reporting', 'reporting'),
    section('Automations', 'automations'),
    section('Integrations', 'integrations'),
    section(
      'For end users',
      'for-end-users',
      'Guides for day-to-day use of OpenLM — checking license availability, understanding your dashboard, and what to do when you get a denial.'
    ),
    section('MCP reporting server', 'mcp-reporting-server'),
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description:
          'API, glossary, and service index for the OpenLM Platform.',
      },
      items: [
        'glossary',
        'service-index',
      ],
    },
    section('Changelog', 'changelog'),
  ],
};

module.exports = sidebars;
