// Per-platform monitoring facts shown by <PlatformFacts />.
// Source of truth: the internal "SaaS platforms" tracking sheet (Frequency +
// "LAC support" columns), verified 2026-07-15. Keys are the doc page slugs
// under docs/cloud/data-collection/connect-license-managers/saas-platforms/.
// `lac` lists the License Access Control operations the integration supports;
// omit the key (or use an empty array) when LAC is not supported.

const PLATFORM_FACTS = {
  'activecampaign': { frequency: 'Daily' },
  'adobe-cloud': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'altair': { frequency: 'Daily' },
  'apollo-io': { frequency: 'Daily', lac: ['Add', 'Allocate', 'Deallocate'] },
  'arcgis': { frequency: 'Daily' },
  'atlas-mongodb': { frequency: 'Daily' },
  'atlassian-confluence-cloud': { frequency: 'Daily' },
  'autodesk-cloud': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'bamboohr': { frequency: 'Daily' },
  'bentley': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'buddy': { frequency: 'Daily' },
  'calamari': { frequency: 'Daily' },
  'canva': { frequency: 'Daily' },
  'claude-ai': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'cloudflare': { frequency: 'Daily' },
  'cursor-ai': { frequency: 'Daily', lac: ['Add', 'Delete'] },
  'docusign': { frequency: 'Daily' },
  'figma': { frequency: 'Daily' },
  'firebase': { frequency: 'Daily' },
  'float': { frequency: 'Daily' },
  'fluida': { frequency: 'Daily' },
  'freshchat': { frequency: 'Daily' },
  'freshdesk': { frequency: 'Daily' },
  'frontegg': { frequency: 'Daily' },
  'github-copilot': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'gitlab': { frequency: 'Daily' },
  'google-analytics': { frequency: 'Daily' },
  'google-workspace': { frequency: 'Daily' },
  'grammarly': { frequency: 'Daily', lac: ['Add', 'Delete'] },
  'hubspot': { frequency: 'Daily' },
  'humaans': { frequency: 'Daily' },
  'insightful': { frequency: 'Daily' },
  'insightly': { frequency: 'Daily' },
  'intergraph': { frequency: 'Every minute' },
  'jetbrains-cloud': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'jira': { frequency: 'Daily' },
  'launchdarkly': { frequency: 'Daily' },
  'linkedin-company-page': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'linkedin-sales-navigator': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'monday': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'notion': { frequency: 'Daily' },
  'odoo': { frequency: 'Daily' },
  'office-365-azure': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'openlm-license-manager': { frequency: 'Daily' },
  'pagerduty': { frequency: 'Daily' },
  'personio': { frequency: 'Daily' },
  'pipedrive': { frequency: 'Daily' },
  'quicksight': { frequency: 'Daily' },
  'really-simple-systems': { frequency: 'Daily' },
  'rentman': { frequency: 'Daily' },
  'sage-hr': { frequency: 'Daily' },
  'salesflare': { frequency: 'Daily' },
  'salesforce': { frequency: 'Daily' },
  'sentry': { frequency: 'Daily' },
  'swaggerhub': { frequency: 'Daily' },
  'syncfusion': { frequency: 'Daily', lac: ['Add', 'Delete', 'Allocate', 'Deallocate'] },
  'tabnine': { frequency: 'Daily' },
  'teamcity': { frequency: 'Daily' },
  'vertex-ai': { frequency: 'Daily' },
  'youtrack': { frequency: 'Daily' },
  'zenefits': { frequency: 'Daily' },
  'zoho-one': { frequency: 'Daily' },
  'zoom': { frequency: 'Daily' },
  'zoominfo': { frequency: 'Daily', lac: ['Add', 'Allocate', 'Deallocate'] },
};

export default PLATFORM_FACTS;
