extends: existence
message: "Verify your use of '%s' with the Splunk product terminology guidelines. Use a definite article only if the product acts as an adjective."
link: 'https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Terminology'
level: warning
ignorecase: true
tokens:
  - '(?:the|The) (?:Splunk IT Cloud|Splunk Security Cloud|Splunk Observability Cloud)'
